project_id = "ytixqgkzqgeoxrbmjqbo"

[functions.chat-kera]
verify_jwt = false

[functions.providers-status]
verify_jwt = false

[functions.tts-kera]
verify_jwt = false

[functions.monitor-urls]
verify_jwt = false
