project_id = "ytixqgkzqgeoxrbmjqbo"

[functions.chat-kera]
verify_jwt = false

[functions.providers-status]
verify_jwt = false

[functions.tts-kera]
verify_jwt = false

[functions.monitor-urls]
verify_jwt = false

[functions.network-trace]
verify_jwt = false

[functions.network-cron]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.transparencia-scrape]
verify_jwt = false

[functions.ipm-query]
verify_jwt = false
